apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: restyle
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: restyle
    spec:
      containers:
      - name: restyle
        image: gcr.io/restyle/restyle:0.0.2
        env:
        - name: GOOGLE_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: restyle-config
              key: GOOGLE_PROJECT_ID
        - name: GOOGLE_OAUTH_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: restyle-config
              key: GOOGLE_OAUTH_CLIENT_ID
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: restyle-config
              key: GOOGLE_OAUTH_CLIENT_SECRET
        - name: JWT_SHARED_KEY
          valueFrom:
            configMapKeyRef:
              name: restyle-config
              key: JWT_SHARED_KEY
        - name: JWT_SHARED_ENC_KEY
          valueFrom:
            configMapKeyRef:
              name: restyle-config
              key: JWT_SHARED_ENC_KEY
        - name: REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              name: restyle-config
              key: REDIRECT_URL
        ports:
        - containerPort: 8000
