apiVersion: apps/v1
kind: Deployment
metadata:
  name: restyle
spec:
  selector:
    matchLabels:
      run: restyle
  replicas: 2
  template:
    metadata:
      labels:
        run: restyle
    spec:
      containers:
        - name: restyle
          image: gcr.io/project-up-238914/restyle:0.0.1
          ports:
            - containerPort: 8000
              protocol: TCP
