apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoheaders
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: restyle
    spec:
      containers:
      - name: echoheaders
        image: gcr.io/restyle:0.0.1
        ports:
        - containerPort: 8443
