apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: restyle
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: restyle
    spec:
      containers:
      - name: restyle
        image: gcr.io/project-up-238914/restyle:0.0.1
        ports:
        - containerPort: 8000
